# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' OB_AOB_Rcpp
#'
#' Function that can compute OB and AOB (Adaptive-Spending of Tian & Ramdas (2021)) procedure.
#' Setting lambda to 0 gives OB.
#'
#' @param alpha A numeric in [0, 1] for the desired level of type I error control.
#' @param raw.pvalues A vector containing raw p-values.
#' @param gamma A vector : the gamma spending sequence.
#' @param lambda A numeric in [0, 1] : the adaptivity threshold that sets the
#'          threshold for 'candidate' hypothesis. Default to 0.5,
#'          setting lambda to 0 gives 0B the non adaptive versio of AOB.
#'
#' @references Tian, J. and Ramdas, A. (2021). Online control of the familywise
#'             error rate. \emph{Statistical Methods for Medical Research},
#'                          \url{https://journals.sagepub.com/eprint/AYRRKZX7XMTVHKCFYBJY/full}.
#'
#'
OB_AOB_Rcpp <- function(alpha, raw_pvalues, gamma, lambda) {
    .Call(`_OnlineSuperUnif_OB_AOB_Rcpp`, alpha, raw_pvalues, gamma, lambda)
}

#' lord_OnlineSupeUnif
#'
#' Function that computes LORD of Ramdas et al. (2017).
#'
#' @param alpha  A numeric for the desired level of type I error control.
#' @param w0 A numeric in [0, alpha] representing the amount of earning back one wants.
#' @param raw.pvalues A vector containing raw pvalues.
#' @param pCDFlist A list containing the support of the discrete CDF of the p-values.
#'        Each support is represented by a vector in increasing order.
#' @param gamma A vector: the gamma spending sequence.
#'
#' @return A list containing a vector of the sequence of critical values and
#'         a vector of the indices of rejected hypothesis.
#'
#'
#' @references Ramdas, A., Yang, F., Wainwright M.J. and Jordan, M.I. (2017). Online control
#'             of the false discovery rate with decaying memory. \emph{Advances in Neural
#'             Information Processing Systems 30}, 5650-5659.
#'
#'
#' @export
lord_OnlineSuperUnif <- function(alpha, w0, raw_pvalues, gamma) {
    .Call(`_OnlineSuperUnif_lord_OnlineSuperUnif`, alpha, w0, raw_pvalues, gamma)
}

#' saffron_OnlineSuperUnif
#'
#' Function that computes SAFFRON of Ramdas et al. (2018).
#'
#' @param alpha  A numeric for the desired level of type I error control.
#' @param w0 A numeric in [0, alpha] representing the amount of earning back one wants.
#' @param raw.pvalues A vector containing raw p-values.
#' @param pCDFlist A list containing the support of the discrete CDF of the p-values.
#'        Each support is represented by a vector in increasing order.
#' @param gamma A vector: the gamma spending sequence.
#' @param gamma_prime A vector: the gamma prime smoothing sequence (it can be the same as gamma). Default to NULL.
#' @param lambda A numeric in [0, 1] : the threshold for adaptivity.
#'
#' @return A list containing a vector of the sequence of critical values and
#'         a vector of the indices of rejected hypothesis.
#'
#' @reference Ramdas, A., Zrnic, T., Wainwright M.J. and Jordan, M.I. (2018).
#'             SAFFRON: an adaptive algorithm for online control of the false discovery
#'             rate. \emph{Proceedings of the 35th International Conference in Machine
#'             Learning}, 80:4286-4294.
#'
#'
#' @export
saffron_OnlineSuperUnif <- function(alpha, w0, raw_pvalues, gamma, lambda, capping = FALSE) {
    .Call(`_OnlineSuperUnif_saffron_OnlineSuperUnif`, alpha, w0, raw_pvalues, gamma, lambda, capping)
}

#' rho_LORD_ALORD_Rcpp
#'
#' Function that can compute rho-LORD and rho-ALORD.
#' To compute rho_LORD, lambda must be 0 (i.e. we don't threshold for adaptivity to the number of true nulls)
#' When gamma_prime is not provided and 'greedy' set to true, the greedy version of the procedure is computed.
#'
#' @param alpha  A numeric for the desired level of type I error control.
#' @param w0 A numeric in [0, alpha] representing the amount of earning back one wants.
#' @param raw.pvalues A vector containing raw pvalues.
#' @param pCDFlist A list containing the support of the discrete CDF of the p-values.
#'        Each support is represented by a vector in increasing order.
#' @param gamma A vector: the gamma spending sequence.
#' @param lambda A numeric in [0, 1] : the threshold for adaptivity.
#' @param gamma_prime A vector: the gamma prime smoothing sequence (it can be the same as gamma). Default to NULL.
#' @param greedy A boolean to indicate whether we want to perform the greedy version (TRUE) or not (FALSE).
#'        Default to TRUE.
#'
#' @return A list containing a vector of the sequence of critical values and
#'         a vector of the indices of rejected hypothesis.
NULL

#' stepfun
#'
#' Fast step function evaluation.
#' Step function is represented by a single numeric vector under the conditions
#' a) f(x) = x and b) it is complete, meaning that the last value is 1,
#' this is much faster than passing and evaluating R step function objects.
#'
stepfun <- function(x, sfun) {
    .Call(`_OnlineSuperUnif_stepfun`, x, sfun)
}

#' rho_OB_AOB_Rcpp
#'
#' Function that can compute rho-OB and rho-AOB.
#' To compute rho_OB, lambda must be 0 (i.e. we don't threshold for adaptivity to the number of true nulls)
#' When gamma_prime is not provided and 'greedy' set to true, the greedy version of the procedure is computed.
#'
#' @param alpha  A numeric for the desired level of type I error control.
#' @param raw.pvalues A vector containing raw pvalues.
#' @param pCDFlist A list containing the support of the discrete CDF of the p-values.
#'        Each support is represented by a vector in increasing order.
#' @param gamma A vector: the gamma spending sequence.
#' @param lambda A numeric in [0, 1] : the threshold for adaptivity.
#' @param gamma_prime A vector: the gamma prime smoothing sequence (it can be the same as gamma).
#' @param greedy A boolean to indicate whether we want to perform the greedy version (TRUE) or not (FALSE).
#'        Default to TRUE.
#'
#' @return A list containing a vector of the sequence of critical values and
#'         a vector of the indices of rejected hypothesis.
#'
#'
rho_OB_AOB_Rcpp <- function(alpha, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime = numeric(), greedy = TRUE) {
    .Call(`_OnlineSuperUnif_rho_OB_AOB_Rcpp`, alpha, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime, greedy)
}

#'
#'
rho_LORD_ALORD_Rcpp <- function(alpha, w0, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime = numeric(), greedy = TRUE) {
    .Call(`_OnlineSuperUnif_rho_LORD_ALORD_Rcpp`, alpha, w0, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime, greedy)
}

