// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// OB_AOB_Rcpp
List OB_AOB_Rcpp(const double alpha, const NumericVector raw_pvalues, const NumericVector gamma, const double lambda);
RcppExport SEXP _OnlineSuperUnif_OB_AOB_Rcpp(SEXP alphaSEXP, SEXP raw_pvaluesSEXP, SEXP gammaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type raw_pvalues(raw_pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(OB_AOB_Rcpp(alpha, raw_pvalues, gamma, lambda));
    return rcpp_result_gen;
END_RCPP
}
// lord_OnlineSuperUnif
List lord_OnlineSuperUnif(const double alpha, const double w0, const NumericVector raw_pvalues, const NumericVector gamma);
RcppExport SEXP _OnlineSuperUnif_lord_OnlineSuperUnif(SEXP alphaSEXP, SEXP w0SEXP, SEXP raw_pvaluesSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type raw_pvalues(raw_pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(lord_OnlineSuperUnif(alpha, w0, raw_pvalues, gamma));
    return rcpp_result_gen;
END_RCPP
}
// saffron_OnlineSuperUnif
List saffron_OnlineSuperUnif(const double alpha, const double w0, const NumericVector raw_pvalues, const NumericVector gamma, const double lambda, const bool capping);
RcppExport SEXP _OnlineSuperUnif_saffron_OnlineSuperUnif(SEXP alphaSEXP, SEXP w0SEXP, SEXP raw_pvaluesSEXP, SEXP gammaSEXP, SEXP lambdaSEXP, SEXP cappingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type raw_pvalues(raw_pvaluesSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type capping(cappingSEXP);
    rcpp_result_gen = Rcpp::wrap(saffron_OnlineSuperUnif(alpha, w0, raw_pvalues, gamma, lambda, capping));
    return rcpp_result_gen;
END_RCPP
}
// stepfun
double stepfun(double& x, const NumericVector& sfun);
RcppExport SEXP _OnlineSuperUnif_stepfun(SEXP xSEXP, SEXP sfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type sfun(sfunSEXP);
    rcpp_result_gen = Rcpp::wrap(stepfun(x, sfun));
    return rcpp_result_gen;
END_RCPP
}
// rho_OB_AOB_Rcpp
List rho_OB_AOB_Rcpp(const double alpha, const NumericVector raw_pvalues, const List pCDFlist, const NumericVector gamma, const double lambda, const NumericVector gamma_prime, const bool greedy);
RcppExport SEXP _OnlineSuperUnif_rho_OB_AOB_Rcpp(SEXP alphaSEXP, SEXP raw_pvaluesSEXP, SEXP pCDFlistSEXP, SEXP gammaSEXP, SEXP lambdaSEXP, SEXP gamma_primeSEXP, SEXP greedySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type raw_pvalues(raw_pvaluesSEXP);
    Rcpp::traits::input_parameter< const List >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma_prime(gamma_primeSEXP);
    Rcpp::traits::input_parameter< const bool >::type greedy(greedySEXP);
    rcpp_result_gen = Rcpp::wrap(rho_OB_AOB_Rcpp(alpha, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime, greedy));
    return rcpp_result_gen;
END_RCPP
}
// rho_LORD_ALORD_Rcpp
List rho_LORD_ALORD_Rcpp(const double alpha, const double w0, const NumericVector raw_pvalues, const List pCDFlist, const NumericVector gamma, const double lambda, const NumericVector gamma_prime, const bool greedy);
RcppExport SEXP _OnlineSuperUnif_rho_LORD_ALORD_Rcpp(SEXP alphaSEXP, SEXP w0SEXP, SEXP raw_pvaluesSEXP, SEXP pCDFlistSEXP, SEXP gammaSEXP, SEXP lambdaSEXP, SEXP gamma_primeSEXP, SEXP greedySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type raw_pvalues(raw_pvaluesSEXP);
    Rcpp::traits::input_parameter< const List >::type pCDFlist(pCDFlistSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type gamma_prime(gamma_primeSEXP);
    Rcpp::traits::input_parameter< const bool >::type greedy(greedySEXP);
    rcpp_result_gen = Rcpp::wrap(rho_LORD_ALORD_Rcpp(alpha, w0, raw_pvalues, pCDFlist, gamma, lambda, gamma_prime, greedy));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OnlineSuperUnif_OB_AOB_Rcpp", (DL_FUNC) &_OnlineSuperUnif_OB_AOB_Rcpp, 4},
    {"_OnlineSuperUnif_lord_OnlineSuperUnif", (DL_FUNC) &_OnlineSuperUnif_lord_OnlineSuperUnif, 4},
    {"_OnlineSuperUnif_saffron_OnlineSuperUnif", (DL_FUNC) &_OnlineSuperUnif_saffron_OnlineSuperUnif, 6},
    {"_OnlineSuperUnif_stepfun", (DL_FUNC) &_OnlineSuperUnif_stepfun, 2},
    {"_OnlineSuperUnif_rho_OB_AOB_Rcpp", (DL_FUNC) &_OnlineSuperUnif_rho_OB_AOB_Rcpp, 7},
    {"_OnlineSuperUnif_rho_LORD_ALORD_Rcpp", (DL_FUNC) &_OnlineSuperUnif_rho_LORD_ALORD_Rcpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_OnlineSuperUnif(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
