---
title: "Superunifreward_fig"
output: html_document
---

```{r}
library(ggplot2)
library(latex2exp)
library(ggbrace)
```

```{r}
data <- data.frame(c(0, 1), c(0, 1))
names(data)[1] =  "x_diag"
names(data)[2] =  "y_diag"

data_seg_1 <- data.frame(x1 = 0, x2 = 0.25, y1 = 0, y2 = 0)
data_seg_2 <- data.frame(x1 = 0.25, x2 = 0.75, y1 = 0.25, y2 = 0.25)
data_seg_3 <- data.frame(x1 = 0.75, x2 = 1, y1 = 0.75, y2 = 0.75)
data_seg_su <- data.frame(x1 = 0.625, x2 = 0.625, y1 = 0.25, y2 = 0.625)
```

```{r}
plot_sureward <- ggplot(data) + geom_line(aes_string(x = "x_diag", y = "y_diag"), 
                         color = "azure4", linetype = "dashed", lwd = 1) +
               xlab("") + ylab("") +
# stepwise function
               geom_segment(data = data_seg_1, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") + 
               annotate(geom = "point", x = 0, y = 0, color = "darksalmon", size = 3) +
               geom_segment(data = data_seg_2, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") +
               annotate(geom = "point", x = 0.25, y = 0.25, color = "darksalmon", size = 3) +
               geom_segment(data = data_seg_3, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") + 
               annotate(geom = "point", x = 0.75, y = 0.75, color = "darksalmon", size = 3) +
               annotate(geom = "point", x = 1, y = 1, color = "darksalmon", size = 3) +
# su reward 
               geom_segment(data = data_seg_su, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, alpha = 0.6) +
               annotate(geom = "point", x = 0.625, y = 0.25, color = "brown4", size = 3) +
               annotate(geom = "point", x = 0.625, y = 0.625, pch = 25, size = 3, color = "brown4", fill = "brown4") +
               annotate(geom = "point", x = 0.625, y = 0, pch = 25, size = 3, color = "brown4", fill = "brown4") +
               annotate(geom = "text", x = 0.625, y = 0.18, label = TeX('$F_t(\\alpha_t)$'), size = 6) +
               annotate(geom = "text", x = 0.625, y = -0.08, label = TeX('$\\alpha_t$'), size = 6) +
               annotate(geom = "text", x = 0.8, y = 0.43, label = TeX('$\\rho_t = \\alpha_t - F_t(\\alpha_t)$'), size = 6) +
               theme(axis.text=element_text(size=12))

plot_sureward
  
``` 

```{r}
ggsave("superunifreward_fig.png", plot = plot_sureward, width = 16, height = 10, units = "cm")
```

# figure not present in the paper 
```{r}
plot_sureward_differentmagnitude <- ggplot(data) + geom_line(aes_string(x = "x_diag", y = "y_diag"), 
                         color = "azure4", linetype = "dashed", lwd = 1) + 
               xlab("") + ylab("") +
               geom_segment(data = data_seg_1, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") +
               annotate(geom = "point", x = 0, y = 0, color = "darksalmon", size = 3) +
               geom_segment(data = data_seg_2, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") +
               annotate(geom = "point", x = 0.25, y = 0.25, color = "darksalmon", size = 3) +
               geom_segment(data = data_seg_3, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, color = "darksalmon") +
               annotate(geom = "point", x = 0.75, y = 0.75, color = "darksalmon", size = 3) +
               annotate(geom = "point", x = 1, y = 1, color = "darksalmon", size = 3) +
# when su reward is 0 
               annotate(geom = "point", x = 0.75, y = 0.75, color = "darkgreen", size = 3) +
               annotate(geom = "point", x = 0.75, y = 0, pch = 25, size = 3, color = "darkgreen", fill = "darkgreen") +
               annotate(geom = "text", x = 0.7, y = 0.8, label = TeX('$F_t(\\alpha_t) = \\alpha_t$'), size = 6) +
               annotate(geom = "text", x = 0.75, y = -0.08, label = TeX('$\\alpha_t$'), size = 6) +
               
# when su reward is large 
                              geom_segment(data = data_seg_su, aes(x = x1, y = y1, xend = x2, yend = y2), lwd = 1, alpha = 0.6) +
               annotate(geom = "point", x = 0.625, y = 0.25, color = "brown4", size = 3) +
               annotate(geom = "point", x = 0.625, y = 0.625, pch = 25, size = 3, color = "brown4", fill = "brown4") +
               annotate(geom = "point", x = 0.625, y = 0, pch = 25, size = 3, color = "brown4", fill = "brown4") +
               annotate(geom = "text", x = 0.625, y = 0.18, label = TeX('$F_t(\\alpha_t)$'), size = 6) +
               annotate(geom = "text", x = 0.625, y = -0.08, label = TeX('$\\alpha_t$'), size = 6) +
               annotate(geom = "text", x = 0.58, y = 0.43, label = TeX('$\\rho_t'), size = 6) +
              theme(axis.text=element_text(size=12))
plot_sureward_differentmagnitude
```

```{r}
ggsave("superunifreward_small_fig.png", plot = plot_sureward_differentmagnitude, width = 16, height = 10, units = "cm")
```

